package nl.rinis.wzd;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-11-09T23:37:46.149+01:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://www.ciz.nl/rechtspraak/rinis/request/v4", name = "RechtspraakPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RechtspraakPort {

    @WebMethod(operationName = "RechtspraakRequest")
    @WebResult(name = "Response", targetNamespace = "http://www.ciz.nl/rechtspraak/rinis/request/v3", partName = "Response")
    public Response rechtspraakRequest(

        @WebParam(partName = "RechtspraakRequestBericht", name = "RechtspraakRequestBericht", targetNamespace = "http://www.ciz.nl/rechtspraak/rinis/request/v4")
        RechtspraakRequestBericht rechtspraakRequestBericht
    );
}
